[local]
localhost

[mongodb]
mongodb.vijaansh.online

[redis]
redis.vijaansh.online

[mysql]
mysql.vijaansh.online

[rabbitmq]
rabbitmq.vijaansh.online

[catalogue]
catalogue.vijaansh.online

[user]
user.vijaansh.online

[cart]
cart.vijaansh.online

[shipping]
shipping.vijaansh.online

[payment]
payment.vijaansh.online

[frontend]
frontend.vijaansh.online